language: elixir

sudo: required

elixir:
  - 1.8.2

services:
  - redis-server
  - postgresql
  - elasticsearch

env:
  - MIX_ENV=test

addons:
  postgresql: "10"

script:
  - mix credo -a
  - mix test --exclude skip_on_travis

notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: "amCHwsXdmos/JkW8F9I7QFo32VVkt7oEEHTwKzZVE0fYZ2M8Gbdw0JTfpj///OJUI9TUJ6IQxsEbqf4UTF3YNqIUtYOUopljp/H28n4mHOUf282dT+Pikc5FtFFgw7DEdSq1IPIWPC9MyzwnDyP6m+4AortSbm48/p925KnS0uy6b6saPrxpW+MDoyAAdlVJj5oYkcv/CZq+1DMrsrWfPbKMW3II7QzQRkHZsr02pSLth119ShKfNOrhBQQH1hR0wOrlBQY4JH1vXrn5R7ZB7Y5SL9SWrb5ZNFq/icU0Dxf9QSGE8DR08/owS42aJNjIghsZYQ3zTW8x6nbGoqJ8O8TsHwTeqMYtaQLYuQpblUNEJDyZsSHiP3Fmq9x9BEDrKaP/u+YALPXFpo8fLIRmu7TbdJTlmW8A2ag5w1XZSx8GqFjGpDJNaQd9fw1R3qEvZqH1SULwKT4hr41TDTL4KVk4kjnPX5K9KBR2VYpPREGTv1oAKWirII6TgXR0uvfKy1s93lMtalDLVnaEtnmeKfBL7vZ0Ta8vmAaSkZuaoAcSEfyohQXRj49D3OGJBU3Xn9tKXPpUJ6CdpDi4GxZSDxVL7kVA1v5Rfzf2gwjmw0+CaiHtroN2k/cdNjyeC//58uNfNcZd6rs2h+ZVm8W9coKcA1yQH2nrP+zBDx0G/Pk="
