language: elixir
elixir:
  - 1.5.3
otp_release:
  - 20.2
services:
  - redis-server
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - oracle-java8-set-default
before_install:
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb
  - sudo service elasticsearch start
script:
  - mix compile --warnings-as-errors
  - mix credo -a
  - mix test --exclude skip_on_travis
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: oQ+gH/oYwMcB06l1zUNJdmHn5gi4JIXqehJCpqePvw0lc83SlkAgaTeffWL5l7yqXwzTOKMQQcMYeJWMoWmhzKCW0dPDS4pZDtW8Pt7MXd6YhyTbAOodOKXj2UPbihpMtAx8FzniKAVnaPmrqLo8T0R9l1UhcnCiZE3KfrgTgZXuzrMv0Z1k5GB0zTYqkYY3I4AaTn8xLp4clfUI3qeLE8cigxC6ZQ7gUOr0rE5hbmcqJsN0auuIe2aLOU9sVXGPd/efwnW9O1gHcEv7h5f0RH8gkGlvUCSpD6Yvn55O3jOmIxCLFNY0smCLLnK4S5WDgrI0DLEhX0mGeFT1+kI5wQ+iE4xtj5r2KtHaiOg7t63M+CoTbQzk/S8xWpUXG4gidGsXUcsgMVLbronlNGMiFGcub/1dz5tDjT77C1dtDZeWqunLj5R2apW71uK8ouL+cck4ePja1+kCM/0wgPT4TfA9m2lcbnC/AggGO9VFrttL8VqF+czXFwrZgvBqI3f0HSpErDYUoxzejVvhqB+QUFNN4fNHcQ+DIlzHxlAMd0k+7sRoD1NJeq5gcXnRFUJ68PRCQgOD2A+OVQWdTgDDCH05jzVjgOVolRIQ9+krd/R03TUbqIzK6ei8j43SiEZnfpEc3ae3BH7KJlrkPWtCYF1ptxkKStEtmqOzu1dQTBw=
